import { Footer } from "@/components/widgets/footer";
import { Header } from "@/components/widgets/header";
import "@/styles/globals.css";
import { outfit } from "@/styles/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={outfit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
